### PR TITLE
Added null checking on thermostatList events type line 767

### PR DESCRIPTION
**Pull request by samueltbrown**
I installed your awesome ecobee device type but had trouble getting it to poll data due to a null pointer exception encountered on event type checking (line 767).  I added some simple null checking to help bypass this issue.  

Thanks for a great device type, this is awesome!

### CODE REVIEW

**Comment by yracine** [comment]
The latest release 1.7 corrects this issue.

**Comment by samueltbrown** [comment]
Awesome, thanks!

**Comment by yracine** [comment]
Please close the pull request.

**Comment by samueltbrown** [comment]
It appears closed to me, I think you already took care of it.

**Pull request closed without merging**
