### PR TITLE
Hi, you need to remove my copyrigth code from your github

### PR DESCRIPTION
**Pull request by yracine**
Hi, you're  not authorized to post my code here. Please remove all my code, otherwise, I will need to contact the github authorities.  You need to follow the license indicated in the header of all my sources.

Regards.

### CODE REVIEW

**Comment by bridaus** [comment]
are you sure?  Not only do I not recall doing that, but I don't know why
I'd do that?  I'll definitely remove anything, please give me a few days at
least to figure out what I might have.

BTW, your tactics in relation to customer service (I am a customer of
yours) make me a little less inclined to promote your products.  You might
want to take that feedback in consideration, I doubt I'm the only one.

However, I follow rules, and if I have your code in some way (likely
accidental or preceding my memory) I will remove it when I have a moment in
next few days.

**Comment by yracine** [comment]
No, it's not you (bridaus), but somebody else. He was directly notified by email also.

**Comment by Here-Be-Dragons** [comment]
It appears he mistakenly created a pull request with this takedown request
to anyone watching his repository. I guess despite the code being public
and thriving on the open source community nobody is allowed to make
modifications to it. Disappointing stance to say the least.

**Comment by ninjamonkey198206** [comment]
It was likely accidental, and I believe it's for someone else, as the name
on the GitHub listing doesn't match.

And no, you aren't the only one. I'm fairly new to using GitHub, and I know
I've made my fair share of mistakes figuring it out. I've thought myself at
least the basics of 6+ coding and scripting languages recently, and I get
things confused sometimes and things get mixed up. My first reaction when
seeing the communication was "Well, if I've got something up I didn't do it
on purpose. That was a bit rude. A little simple courtesy and not assuming
I was doing it intentionally would've been nice."

**Comment by Vegetadogs** [comment]
Has it been pulled? im following thread. N got an email but wasn't sure if it was me. Sorry if it was me

**Comment by yracine** [comment]
It's not you. You don't need to worry.  It's someone who has been notified by email.  I was contacting him again here.  If  you haven't received an email from me through gmail, this doesn't target you at all.

**Comment by ulizzi** [comment]
Hi Yves, I think I have received this email in error since I have not
posted any of your code on github. Quite frankly I'm not sure I'd even know
how to do that since my only interaction on github was to download the code
that I purchased from you. Please clarify and advise if there was something
that I did strictly in error.

Regards...Frank

**Comment by yracine** [comment]
Hi,

It's not you. It's someone who has previously been notified by email. I was contacting him again here. If you haven't received an email from me through gmail asking you directly (with your first name) to remove my code, this doesn't target you at all.

**Comment by HanOnGit** [comment]
I am new to GitHub and fiddling my way around.  Is it me?  If so, how can I check and discontinue publishing.  BTW, I haven't had the time to learn how to post either.  Just a weekend enthusiast.

**Comment by SatComEng** [comment]
I don't have any of your code on my Github, so please stop spamming me.

**Pull request closed without merging**
